apiVersion: apps/v1
kind: Deployment
metadata:
  name: articledep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article
  template:
    metadata:
      labels:
        app: article
    spec:
      containers:
        - name: article
          image: brahimbtf/article-k3s-app
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: configmapprojetk3s
            - secretRef:
                name: secretprojetk3s
          resources:
            requests:
              memory: 300Mi
              cpu:  200m
            limits:
              memory: 500Mi
              cpu: 300m

