apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartedep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: brahimbtf/cart-k3s-app
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: configmapprojetk3s
            - secretRef:
                name: secretprojetk3s
          resources:
            requests:
              memory: 300Mi
              cpu:  200m
            limits:
              memory: 500Mi
              cpu: 300m



